name: Build Image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Tags
        id: generate-tags
        run: |
          TAGS=()

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            TAGS+=("pr-${{ github.event.number }}")
          else
            TAGS+=("$(date +%Y%m%d)")
            TAGS+=("latest")
          fi

          echo "tags=${TAGS[*]}" >> $GITHUB_OUTPUT
      
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: Containerfile
          image: ${{ github.event.repository.name  }}
          tags: ${{ steps.generate-tags.outputs.tags }}

      - name: Lowercase Registry
        id: lowercase_registry
        uses: ASzc/change-string-case-action@v6
        with:
          string: "ghcr.io/${{ github.repository_owner }}"

      - name: Push Image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ steps.lowercase_registry.outputs.lowercase }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        

